export const ipcChannels = {
  app: {
    getInfo: "bukowskiApp:getInfo",
    openExternal: "bukowskiApp:openExternal",
    reportRuntimeError: "bukowskiApp:reportRuntimeError",
  },
  shell: {
    getBootstrap: "bukowskiShell:getBootstrap",
    searchGlobal: "bukowskiShell:searchGlobal",
    appAction: "bukowskiShell:appAction",
  },
  agents: {
    getMissionControlSnapshot: "bukowskiAgents:getMissionControlSnapshot",
    getAgentsList: "bukowskiAgents:getAgentsList",
    getAgentDetail: "bukowskiAgents:getAgentDetail",
    getRunsList: "bukowskiAgents:getRunsList",
    getModelsSnapshot: "bukowskiAgents:getModelsSnapshot",
    getAIProviderConfigs: "bukowskiAgents:getAIProviderConfigs",
    getConnectorsSnapshot: "bukowskiAgents:getConnectorsSnapshot",
    getAssistantChatSnapshot: "bukowskiAgents:getAssistantChatSnapshot",
    create: "bukowskiAgents:create",
    update: "bukowskiAgents:update",
    setStatus: "bukowskiAgents:setStatus",
    setApprovalMode: "bukowskiAgents:setApprovalMode",
    saveAIProviderConfig: "bukowskiAgents:saveAIProviderConfig",
    testAIProviderConnection: "bukowskiAgents:testAIProviderConnection",
    assignAgentModel: "bukowskiAgents:assignAgentModel",
    createAssistantThread: "bukowskiAgents:createAssistantThread",
    deleteAssistantThread: "bukowskiAgents:deleteAssistantThread",
    setActiveAssistantThread: "bukowskiAgents:setActiveAssistantThread",
    updateAssistantThreadPreferences: "bukowskiAgents:updateAssistantThreadPreferences",
    sendAssistantChatTurn: "bukowskiAgents:sendAssistantChatTurn",
    reviewRun: "bukowskiAgents:reviewRun",
    sendAssistantMessage: "bukowskiAgents:sendAssistantMessage",
    createDraftRunFromChat: "bukowskiAgents:createDraftRunFromChat",
  },
  overview: {
    getSnapshot: "bukowskiOverview:getSnapshot",
    getTimeline: "bukowskiOverview:getTimeline",
  },
  assets: {
    getList: "bukowskiAssets:getList",
    getSummary: "bukowskiAssets:getSummary",
    getOverview: "bukowskiAssets:getOverview",
    getDetail: "bukowskiAssets:getDetail",
    assignMove: "bukowskiAssets:assignMove",
    create: "bukowskiAssets:create",
    update: "bukowskiAssets:update",
    archive: "bukowskiAssets:archive",
  },
  packing: {
    getList: "bukowskiPacking:getList",
    getDetail: "bukowskiPacking:getDetail",
    create: "bukowskiPacking:create",
    returnItems: "bukowskiPacking:returnItems",
  },
  incidents: {
    getList: "bukowskiIncidents:getList",
    report: "bukowskiIncidents:report",
  },
  projects: {
    getList: "bukowskiProjects:getList",
    getDetail: "bukowskiProjects:getDetail",
    getCatalog: "bukowskiProjects:getCatalog",
    create: "bukowskiProjects:create",
    update: "bukowskiProjects:update",
    delete: "bukowskiProjects:delete",
    createUnit: "bukowskiProjects:createUnit",
    updateUnit: "bukowskiProjects:updateUnit",
    deleteUnit: "bukowskiProjects:deleteUnit",
    assignCrewToUnit: "bukowskiProjects:assignCrewToUnit",
    unassignCrewFromUnit: "bukowskiProjects:unassignCrewFromUnit",
  },
  catalog: {
    getSnapshot: "bukowskiCatalog:getSnapshot",
    create: "bukowskiCatalog:create",
    update: "bukowskiCatalog:update",
    delete: "bukowskiCatalog:delete",
  },
  rma: {
    getSnapshot: "bukowskiRma:getSnapshot",
    getDetail: "bukowskiRma:getDetail",
    create: "bukowskiRma:create",
    update: "bukowskiRma:update",
  },
  finance: {
    getOverview: "bukowskiFinance:getOverview",
    getCostLinks: "bukowskiFinance:getCostLinks",
    getEntries: "bukowskiFinance:getEntries",
  },
} as const;
